version: "3"
services:
  exercism-c:
    build: c
    volumes:
      - ./c:/c
  exercism-go:
    build: go
    volumes:
      - ./go:/go
  exercism-python:
    build: python
    volumes:
      - ./python:/python
  exercism-ruby:
    build: ruby
    volumes:
      - ./ruby:/ruby
  exercism-rust:
    build: rust
    volumes:
      - ./rust:/rust
